[variables]
PYTHONPATH = "/app"

[phases.setup]
# Use Nix's Python with pip included
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.virtualenv", "curl", "netcat-gnu", "gcc", "postgresql"]

[phases.install]
# Let Nixpacks handle the Python dependency installation automatically
# Remove manual pip commands since Nixpacks will handle requirements.txt

[phases.build]
# Optional verification - but remove pip upgrade since it's handled by Nix
cmds = [
    "python3 -c \"import fastapi; print('FastAPI available')\"",
    "python3 -c \"import uvicorn; print('Uvicorn available')\""
]

[start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"