import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from "./providers/AuthProvider";
import {ThemeProvider} from "@/components/ThemeProvider";
import {ReactScan} from "@/components/ReactScan";
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <ReactScan/>
        <body>
        <ThemeProvider
            attribute={'class'}
            defaultTheme={'system'}
            enableSystem={true}
            disableTransitionOnChange
        >
            <AuthProvider>
                {children}
            </AuthProvider>
        </ThemeProvider>
        <Toaster/>

        </body>
        </html>
    );
}
