"""Add wallet monitoring tables

Revision ID: 0cd46bf81b0e
Revises: 55c0c110109f
Create Date: 2025-06-20 22:42:35.381424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cd46bf81b0e'
down_revision: Union[str, None] = '55c0c110109f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coinage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_addresses_address'), 'monitored_addresses', ['address'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitored_address_id', sa.Integer(), nullable=False),
    sa.Column('txid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_address_id'], ['monitored_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_txid'), 'wallet_transactions', ['txid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_txid'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_monitored_addresses_address'), table_name='monitored_addresses')
    op.drop_table('monitored_addresses')
    op.drop_table('coinage')
    # ### end Alembic commands ###
